### ISSUE TITLE
WebDAV problem - file with spaces in the name is not available

### ISSUE THREAD

**Issue by DaMaNic2022** [distribyted/distribyted#182]
The "Bullet Train.mkv" torrent has been added to the program. As a Webdav resource is visible, when you try to download an error, in the logs you can see that there was an attempt to download the file "Bullet"

**Comment by ajnavarro** [comment]
Hi @DaMaNic2022 thanks for the heads up!

I'll have a look into it as soon I have some time.

**Comment by pataquets** [comment]
Gettin' familiar with the code here. In case anyone else wants to give it a stab at troubleshooting this, I'm dropping an example torrent entry for the config YAML which contains spaces:
``` yaml
  - name: demo
    torrents:
     - magnet_uri: "magnet:?xt=urn:btih:c9e15763f722f23e98a29decdfae341b98d53056&dn=Cosmos+Laundromat"
```
Don't worry about licensing and MPAA issues, [Cosmos Laundromat](https://en.wikipedia.org/wiki/Cosmos_Laundromat) is an "open movie".

However, using Nautilus' built-in WebDAV client, I've succeeded at downloading the MP4 file to my desktop. @DaMaNic2022: Can you test it to rule out some client-side issue? Which client are you using?

Also, accessing http://localhost:4444/fs/demo/Cosmos%20Laundromat/Cosmos%20Laundromat.mp4 with the above file works, too.
