### ISSUE TITLE
Mounted torrents are not accessible from host and other containers in Docker.

### ISSUE THREAD

**Issue by ismailkarsli** [distribyted/distribyted#35]
I was trying to set up an on-demand media server with Distribyted, Sonarr, Jellyfin. But I got stuck at accessing mounts from outside container.

Other volume bindings are working normally but when I try to cd mounts folder, getting `/bin/sh: 40: cd: can't cd to multimedia` error. In host (Windows), multimedia folder is just empty.

Here's my docker-compose file:
```
version: "2"
services:
  distribyted:
    container_name: distribyted
    image: distribyted/distribyted:latest
    restart: unless-stopped
    ports:
      - "4444:4444/tcp"
    volumes:
      - ${MOUNT_POINT}/torrent-mounts:/distribyted-data/mountpoints:shared
      - ${MOUNT_POINT}/config/distribyted/metadata:/distribyted-data/metadata
      - ${MOUNT_POINT}/config/distribyted/config:/distribyted-data/config
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ${MOUNT_POINT}/config/sonarr/config:/config
      - ${MOUNT_POINT}/tvseries:/tv
      - ${MOUNT_POINT}/torrent-mounts:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
```
