### ISSUE TITLE
Improve configuration file structure to support several interfaces.

### ISSUE THREAD

**Issue by ajnavarro** [distribyted/distribyted#42]
Right now, configuration structure is really tied to fuse implementation. We want to support several interfaces (fuse, WebDAV, HTTP, and so on), so we need to change the configuration file a bit.

Initial idea:

```yaml
global_cache_size: 1024
metadata_folder: ./distribyted-data/metadata

routes:
  - name: multimedia
    torrents:
      - magnet_uri: "MAGNET_URI"
      - magnet_uri: "MAGNET_URI"
    fuse:
      allow_other: true
      path: ./path/to/mountpoint
    webdav:
      port: 1233    
```
